/*
 * Copyright (C) 2016 Joshua Yuan
 *
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
package com.joshuayuan.eartraining;

import android.content.Intent;
import android.content.pm.ActivityInfo;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;

/**
 * The first screen that appears when the user opens the app.
 * Intervals and chords are generated by an algorithm that combines multiple sound files.
 * Each of these sound files contains a recording of a single piano note.
 * @author Joshua Yuan
 */
public class MainActivity extends AppCompatActivity {
    /**
     * Loads the first screen of the android app.
     * The screen orientation is locked to portrait.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
    }

    /**
     * Begins the interval activity.
     * @param view The Internal button pressed.
     */
    public void openIntervals(View view) {
        Intent intent = new Intent(this, IntervalsActivity.class);
        startActivity(intent);
    }

    /**
     * Begins the chords activity.
     * @param view The Chords button pressed.
     */
    public void openChords(View view) {
        Intent intent = new Intent(this, ChordsActivity.class);
        startActivity(intent);
    }

    /**
     * Begins the cadences activity.
     * @param view The Cadences button pressed.
     */
    public void openCadences(View view) {
        Intent intent = new Intent(this, CadencesActivity.class);
        startActivity(intent);
    }

    /**
     * Begins the chord progression activity.
     * @param view The Chord Progressions button pressed.
     */
    public void openChordProgressions(View view) {
        Intent intent = new Intent(this, ChordProgression.class);
        startActivity(intent);
    }

    /**
     * Opens the settings window.
     * @param view The Settings button pressed.
     */
    public void openSettings(View view) {
        Intent intent = new Intent(this, PreferencesActivity.class);
        startActivity(intent);
    }

    /**
     * Begins the high score activity.
     * @param view The High Scores button pressed.
     */
    public void openHighScores(View view) {
        Intent intent = new Intent(this, HighScoresActivity.class);
        startActivity(intent);
    }
}
